function [h] = SpatialChannelModel(u,s,d_u,d_s,t,N,M,Pn,sigma_SF,G_BS,G_MS,G_BS_theta_n_m_AoD,G_MS_theta_n_m_AoA,theta_BS,theta_MS,theta_n_m_AoD,theta_n_m_AoA,Phi_n_m,Phi_LOS,v,theta_v,K)
    
    k = 2*pi;
    h = [];
    if(u==1)
        d_u = 0;
    end
    if(s==1)
        d_s = 0;
    end
    for n = 1:N
        sum = 0;
		for m = 1:M
			sum = sum + ...
                sqrt(G_BS_theta_n_m_AoD(n,m))*...
				sqrt(G_MS_theta_n_m_AoA(n,m))*...
                exp(1j*k*d_s*sind(theta_n_m_AoD(n,m)))*...
                exp(1j*k*d_u*sind(theta_n_m_AoA(n,m)))*...
                exp(1j*Phi_n_m(n,m))*...
				exp(1j*k*abs(v)*cosd(theta_n_m_AoA(n,m)-theta_v)*t);
		end
		h(n) = sqrt(Pn(n)*sigma_SF/M)*sum;
        h = sqrt(1/(K+1))*h;
        h(1) = h(1) + 10^0.4*sqrt(K/(K+1))* ...
                sqrt(G_BS)*sqrt(G_MS)*...
                exp(1j*k*d_s*sind(theta_BS))*...
                exp(1j*k*d_u*sind(theta_MS))*...
                exp(1j*Phi_LOS)*...
				exp(1j*k*abs(v)*cosd(theta_MS-theta_v)*t);
% 		for m = 1:M
% 			sum = sum + ...
%                 exp(1j*k*d_s*sind(theta_n_m_AoD(n,m)))*...
%                 exp(1j*k*d_u*sind(theta_n_m_AoA(n,m)))*...
%                 exp(1j*Phi_n_m(n,m))*...
% 				exp(1j*k*abs(v)*cosd(theta_n_m_AoA(n,m)-theta_v)*t);
% 		end
% 		h(n) = sqrt(Pn(n)*sigma_SF/M)*sum;

    end
end